[tool.semantic_release]
version_variable = "orders/__init__.py:__version__"
upload_to_pypi = false
prerelease_token = "beta"
# La l칩gica de ramas/canales se maneja en el workflow de GitHub Actions
# Documentaci칩n: https://python-semantic-release.readthedocs.io/en/latest/pre-releases.html
# Puedes cambiar upload_to_pypi a true si vas a publicar en PyPI
# Ajusta version_variable si tu version est치 en otro archivo
# Documentaci칩n: https://python-semantic-release.readthedocs.io/en/latest/configuration.html
changelog_file = "CHANGELOG.md"
commit_message = "chore(release): {version} [skip ci]"

[tool.semantic_release.publish]
upload_to_pypi = false

[tool.semantic_release.changelog]
changelog_sections = ["feature", "fix", "breaking", "documentation", "performance", "refactor", "test", "build", "ci", "chore"]

[tool.semantic_release.commit_parser]
allowed_tags = ["feature", "fix", "breaking", "documentation", "performance", "refactor", "test", "build", "ci", "chore"]
