openapi: 3.0.3
info:
  title: Come-Jale API
  version: 1.0.0
  description: API REST para gestión de productos, pedidos y facturas con autenticación JWT.
servers:
  - url: http://localhost:8000
paths:
  /api/token/:
    post:
      summary: Obtener token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Token JWT obtenido
        '401':
          description: Credenciales inválidas
  /api/token/refresh/:
    post:
      summary: Refrescar token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh:
                  type: string
      responses:
        '200':
          description: Token refrescado
        '401':
          description: Token inválido
  /api/productos/:
    get:
      summary: Listar productos
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de productos
    post:
      summary: Crear producto
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Producto'
      responses:
        '201':
          description: Producto creado
        '401':
          description: No autenticado
  /api/productos/{id}/:
    get:
      summary: Detalle de producto
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalle del producto
        '404':
          description: No encontrado
    put:
      summary: Actualizar producto
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Producto'
      responses:
        '200':
          description: Producto actualizado
    delete:
      summary: Eliminar producto
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Producto eliminado
  /api/pedidos/:
    get:
      summary: Listar pedidos
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de pedidos
    post:
      summary: Crear pedido
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pedido'
      responses:
        '201':
          description: Pedido creado
  /api/pedidos/{id}/:
    get:
      summary: Detalle de pedido
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalle del pedido
        '404':
          description: No encontrado
    put:
      summary: Actualizar pedido
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pedido'
      responses:
        '200':
          description: Pedido actualizado
    delete:
      summary: Eliminar pedido
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Pedido eliminado
  /api/facturas/:
    get:
      summary: Listar facturas
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de facturas
    post:
      summary: Crear factura
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Factura'
      responses:
        '201':
          description: Factura creada
  /api/facturas/{id}/:
    get:
      summary: Detalle de factura
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalle de la factura
        '404':
          description: No encontrado
    put:
      summary: Actualizar factura
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Factura'
      responses:
        '200':
          description: Factura actualizada
    delete:
      summary: Eliminar factura
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Factura eliminada
  /api/usuarios/:
    get:
      summary: Listar usuarios (solo admin)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de usuarios
        '403':
          description: No autorizado
  /api/rutas/:
    get:
      summary: Listar rutas
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de rutas
    post:
      summary: Crear ruta
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ruta'
      responses:
        '201':
          description: Ruta creada
        '401':
          description: No autenticado
  /api/rutas/{id}/:
    get:
      summary: Detalle de ruta
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalle de la ruta
        '404':
          description: No encontrado
    put:
      summary: Actualizar ruta
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ruta'
      responses:
        '200':
          description: Ruta actualizada
    delete:
      summary: Eliminar ruta
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Ruta eliminada
  /api/entregas/:
    get:
      summary: Listar entregas
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de entregas
    post:
      summary: Crear entrega
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entrega'
      responses:
        '201':
          description: Entrega creada
        '401':
          description: No autenticado
  /api/entregas/{id}/:
    get:
      summary: Detalle de entrega
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalle de la entrega
        '404':
          description: No encontrado
    put:
      summary: Actualizar entrega
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entrega'
      responses:
        '200':
          description: Entrega actualizada
    delete:
      summary: Eliminar entrega
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Entrega eliminada
  /api/clientes-ruta/:
    get:
      summary: Listar clientes por ruta
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de clientes por ruta
    post:
      summary: Asociar cliente a ruta
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClienteRuta'
      responses:
        '201':
          description: Asociación creada
        '401':
          description: No autenticado
  /api/clientes-ruta/{id}/:
    get:
      summary: Detalle de cliente en ruta
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detalle de la asociación
        '404':
          description: No encontrado
    put:
      summary: Actualizar cliente en ruta
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClienteRuta'
      responses:
        '200':
          description: Asociación actualizada
    delete:
      summary: Eliminar cliente de ruta
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Asociación eliminada
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Producto:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string
        precio:
          type: number
        descripcion:
          type: string
        categoria:
          type: string
        subcategoria:
          type: string
        imagen:
          type: string
    Pedido:
      type: object
      properties:
        id:
          type: integer
        cliente:
          type: integer
        vendedor:
          type: integer
        repartidor:
          type: integer
        productos:
          type: array
          items:
            type: integer
        direccion_entrega:
          type: string
        contacto:
          type: string
        info_adicional:
          type: string
        estado:
          type: string
        fecha_creacion:
          type: string
          format: date-time
    Factura:
      type: object
      properties:
        id:
          type: integer
        pedido:
          type: integer
        nombre_vendedor:
          type: string
        domicilio_vendedor:
          type: string
        nombre_destinatario:
          type: string
        domicilio_destinatario:
          type: string
        descripcion_mercancias:
          type: string
        tipo_embalaje:
          type: string
        marcas:
          type: string
        numeros:
          type: string
        clases:
          type: string
        cantidades:
          type: string
        termino_comercial:
          type: string
        fletes:
          type: number
        seguro:
          type: number
        lugar_expedicion:
          type: string
        fecha_expedicion:
          type: string
          format: date
        metodo_pago:
          type: string
        monto_total:
          type: number
    Ruta:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string
        descripcion:
          type: string
        activa:
          type: boolean
    Entrega:
      type: object
      properties:
        id:
          type: integer
        pedido:
          type: integer
        repartidor:
          type: integer
        ruta:
          type: integer
        fecha_asignacion:
          type: string
          format: date-time
        fecha_entrega:
          type: string
          format: date-time
        estado:
          type: string
        ubicacion_actual:
          type: string
    ClienteRuta:
      type: object
      properties:
        id:
          type: integer
        cliente:
          type: integer
        ruta:
          type: integer
        latitud:
          type: number
        longitud:
          type: number
        direccion:
          type: string
